name: "Boot Start SSHD"
category: "System"
description: "Start Termux sshd on device boot via RUN_COMMAND intent"
enabled: true

triggers:
  - type: device_boot

actions:
  # Wait for system to settle after boot
  - type: wait
    seconds: 15

  # Start sshd via Termux RUN_COMMAND intent
  - type: shell
    command: "am startservice --user 0 -n com.termux/com.termux.app.RunCommandService -a com.termux.RUN_COMMAND --es com.termux.RUN_COMMAND_PATH '/data/data/com.termux/files/home/.termux/tasker/start-sshd.sh' --ez com.termux.RUN_COMMAND_BACKGROUND 'true'"
    root: false
    block: true

  - type: notification
    title: "SSHD Started"
    text: "Termux sshd launched on boot"
    channel_type: 0
