name: "BT Disconnect XM5"
category: "Bluetooth"
description: "Disconnect WF-1000XM5 headphones from phone on demand (HTTP endpoint + quick tile)"
enabled: true

variables:
  - name: bt_mac
    type: string
    # TODO: Replace with your WF-1000XM5 MAC address (Settings > Connected Devices > WF-1000XM5 > gear icon)
    value: "XX:XX:XX:XX:XX:XX"
  - name: result
    type: string
    value: ""

triggers:
  - type: http_server
    identifier: "bt-disconnect"
    send_response: true

actions:
  # Disconnect via shell (Android 13+ cmd bluetooth_manager)
  - type: shell
    command: "cmd bluetooth_manager disconnect {lv=bt_mac}"
    root: false
    output_var: "result"

  - type: notification
    title: "BT Disconnected"
    text: "WF-1000XM5 disconnected from phone"
    channel_type: 2

  - type: http_response
    code: "OK"
    text: '{"status": "disconnected", "device": "WF-1000XM5"}'

constraints:
  - type: bluetooth
    device: "WF-1000XM5"
    state: "connected"
