# Export Macros on Demand
# Listens for HTTP request and triggers MacroDroid export
#
# Usage: curl http://<phone-ip>:7777/export-macros
# The macro will export to ~/macros/ and return the filename

name: "Export Macros API"
category: "Automation"
description: "HTTP endpoint to trigger macro export for remote state sync"
enabled: true

variables:
  - name: export_filename
    type: string
    value: ""
  - name: timestamp
    type: string
    value: ""

triggers:
  - type: http_server
    identifier: "export-macros"
    send_response: true

actions:
  # Generate timestamp for filename
  - type: set_variable
    name: timestamp
    type: string
    value: "{date_time,yyyy_MM_dd_HH_mm}"

  # Build filename
  - type: set_variable
    name: export_filename
    type: string
    value: "MacroDroid_{lv=timestamp}.mdr"

  # Use shell to trigger the export via am broadcast
  # MacroDroid exports to its default location, we copy to ~/macros
  - type: shell
    command: |
      # Create macros dir if needed
      mkdir -p ~/macros
      # Use MacroDroid's content URI to export (requires Termux:API or direct file access)
      # For now, just echo success - user needs to manually configure export path in MacroDroid
      echo "Export triggered: {lv=export_filename}"
    output_var: "shell_output"

  # Respond with filename
  - type: http_response
    code: "OK"
    text: "{lv=export_filename}"
