# Games Open Tracker
# Reports to /phone when any tracked game is opened

name: "Games Open"
category: "Telemetry"
description: "Track game app opens"
enabled: true

triggers:
  - type: app_launched
    apps: ["Thronefall", "Slice & Dice", "20 Minutes Till Dawn", "OneBit Adventure"]
    packages:
      - "com.doghowlgames.thronefall"
      - "com.com.tann.dice"
      - "com.Flanne.MinutesTillDawn.roguelike.shooting.gp"
      - "com.GalacticSlice.OneBitAdventure"
    launched: true

actions:
  - type: http_request
    url: "http://100.66.10.74:7777/phone"
    method: POST
    body: '{"app": "game", "action": "open"}'
    content_type: "application/json"
