# Games Open Tracker with Fallback
# Reports to /phone when any tracked game is opened
# If server unreachable, triggers local enforcement

name: "Games Open"
category: "Telemetry"
description: "Track game opens, fallback to local if server down"
enabled: true

variables:
  - name: response_code
    type: integer
    value: 0

triggers:
  - type: app_launched
    apps: ["Thronefall", "Slice & Dice", "20 Minutes Till Dawn", "OneBit Adventure"]
    packages:
      - "com.doghowlgames.thronefall"
      - "com.com.tann.dice"
      - "com.Flanne.MinutesTillDawn.roguelike.shooting.gp"
      - "com.GalacticSlice.OneBitAdventure"
    launched: true

actions:
  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"app": "game", "action": "open"}'
    content_type: "application/json"
    code_var: "response_code"
    block_next: true
    timeout: 5

  # If server unreachable (code != 200), trigger local fallback
  - type: if
    conditions:
      - type: variable
        variable: "response_code"
        var_type: integer
        comparison: not_equals
        value: 200
        local_var: true

  # Force run local management for this app
  - type: run_macro
    macro_name: "Thronefall Management"

  # Enable all local fallbacks for future events
  - type: run_macro
    macro_name: "Enable Local Fallback"

  - type: end_if
