# Geofence Gym Enter Telemetry + Logging
# Reports when entering the gym

name: "Geofence Gym Enter"
category: "Geofence"
description: "Track entering gym geofence"
enabled: true

triggers:
  - type: geofence
    geofence_id: "7fa61f1d-fcc7-4ffc-8b83-0e5b6ba0e0dd"
    enter: true

actions:
  # Log: macro triggered
  - type: shell
    command: 'mkdir -p /storage/emulated/0/MacroDroid/logs && echo "{system_time} INFO geofence-gym ENTER" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"location": "gym", "action": "enter"}'
    content_type: "application/json"
