# Geofence Gym Enter Telemetry
# Reports when entering the gym - pure location tracking

name: "Geofence Gym Enter"
category: "Geofence"
description: "Track entering gym geofence"
enabled: true

triggers:
  - type: geofence
    geofence_id: "7fa61f1d-fcc7-4ffc-8b83-0e5b6ba0e0dd"
    enter: true

actions:
  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"location": "gym", "action": "enter"}'
    content_type: "application/json"
