# Geofence Home Enter Telemetry + Logging
# Reports when arriving home

name: "Geofence Home Enter"
category: "Telemetry"
description: "Track entering home geofence"
enabled: true

triggers:
  - type: geofence
    geofence_id: "1e4e4f0d-ccd8-40a2-b84a-6027a2843cb8"
    enter: true

actions:
  # Log: macro triggered
  - type: shell
    command: 'mkdir -p /storage/emulated/0/MacroDroid/logs && echo "{system_time} INFO geofence-home ENTER" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"location": "home", "action": "enter"}'
    content_type: "application/json"
