# Shizuku Death Logger
#
# Detects Shizuku death and logs rich context to understand WHEN and WHY it dies:
#   - Timestamp
#   - Screen state (on/locked/off)
#   - WiFi SSID
#   - Battery level + charging state
#   - Whether Shizuku was previously known alive
#
# Triggers on screen on AND screen off to catch Samsung's screen-lock kill behavior.
# Uses RUNNING/STOPPED string outputs to avoid empty-string comparison issues.
# Tracks state via global shizuku_dead to suppress repeat notifications.

name: "Shizuku Death Logger"
category: "System"
description: "Logs Shizuku state changes with context on screen on/off"
enabled: true

variables:
  - name: shizuku_status
    type: string
    value: ""
  - name: log_line
    type: string
    value: ""

global_variables:
  - name: shizuku_dead
    type: boolean
    value: false

triggers:
  - type: screen_on
    screen_on: true

  - type: screen_on
    screen_on: false

actions:
  # Check Shizuku process via MacroDroid helper (elevated perms needed to see other app processes)
  # useHelper=true routes through Shizuku → can see all PIDs
  # If Shizuku is dead → helper has no elevated perms → pidof returns nothing → STOPPED
  - type: shell
    command: 'pidof moe.shizuku.privileged.api > /dev/null 2>&1 && echo RUNNING || echo STOPPED'
    output_var: "shizuku_status"
    use_helper: true

  # Build log line: all context in one shell script (no folded yaml, no broken magic vars)
  # Battery via dumpsys, WiFi SSID via getprop/dumpsys, timestamp via date command
  - type: shell
    command: 'TS=$(date "+%Y-%m-%d %H:%M:%S"); BAT=$(dumpsys battery 2>/dev/null | grep -m1 "level:" | tr -d " " | cut -d: -f2); SSID=$(dumpsys wifi 2>/dev/null | grep -m1 "SSID:" | sed "s/.*SSID: //;s/,.*//" | tr -d " "); CHG=$(dumpsys battery 2>/dev/null | grep -m1 "status:" | tr -d " " | cut -d: -f2); mkdir -p /storage/emulated/0/MacroDroid/logs; echo "$TS shizuku={lv=shizuku_status} wifi=$SSID bat=${BAT}% charge=$CHG" >> /storage/emulated/0/MacroDroid/logs/shizuku.log'
    block: false

  # === Newly dead: was alive, now stopped ===
  - type: if
    conditions:
      - type: variable
        variable: "shizuku_status"
        var_type: string
        comparison: equals
        value: "STOPPED"
        local_var: true

  - type: if
    conditions:
      - type: variable
        variable: "shizuku_dead"
        var_type: boolean
        comparison: equals
        value: "false"

  - type: set_variable
    name: "shizuku_dead"
    value: "true"
    var_type: boolean

  - type: notification
    title: "Shizuku Died"
    text: "Enforcement offline — tap to restart Shizuku"
    channel_type: 1

  - type: vibrate
    pattern: [0, 300, 200, 300]

  # Log death event with full context
  - type: shell
    command: 'TS=$(date "+%Y-%m-%d %H:%M:%S"); BAT=$(dumpsys battery 2>/dev/null | grep -m1 "level:" | tr -d " " | cut -d: -f2); SSID=$(dumpsys wifi 2>/dev/null | grep -m1 "SSID:" | sed "s/.*SSID: //;s/,.*//" | tr -d " "); echo "$TS SHIZUKU_DIED wifi=$SSID bat=${BAT}%" >> /storage/emulated/0/MacroDroid/logs/shizuku.log'
    block: false

  - type: launch_app
    app: "Shizuku"
    package: "moe.shizuku.privileged.api"

  - type: http_request
    url: "http://100.66.10.74:7777/phone"
    method: POST
    body: '{"event": "shizuku_died", "time": "{system_time}"}'
    content_type: "application/json"
    block: false

  - type: end_if  # was previously alive

  - type: end_if  # STOPPED

  # === Recovered: was dead, now running ===
  - type: if
    conditions:
      - type: variable
        variable: "shizuku_status"
        var_type: string
        comparison: equals
        value: "RUNNING"
        local_var: true

  - type: if
    conditions:
      - type: variable
        variable: "shizuku_dead"
        var_type: boolean
        comparison: equals
        value: "true"

  - type: set_variable
    name: "shizuku_dead"
    value: "false"
    var_type: boolean

  - type: shell
    command: 'TS=$(date "+%Y-%m-%d %H:%M:%S"); SSID=$(dumpsys wifi 2>/dev/null | grep -m1 "SSID:" | sed "s/.*SSID: //;s/,.*//" | tr -d " "); echo "$TS SHIZUKU_RESTORED wifi=$SSID" >> /storage/emulated/0/MacroDroid/logs/shizuku.log'
    block: false

  - type: http_request
    url: "http://100.66.10.74:7777/phone"
    method: POST
    body: '{"event": "shizuku_restored", "time": "{system_time}"}'
    content_type: "application/json"
    block: false

  - type: end_if  # was previously dead
  - type: end_if  # RUNNING
