# Twitter Open Tracker
# Reports to /phone when Twitter is opened

name: "Twitter Open"
category: "Telemetry"
description: "Track Twitter app opens"
enabled: true

triggers:
  - type: app_launched
    apps: ["X"]
    packages: ["com.twitter.android"]
    launched: true

actions:
  - type: http_request
    url: "http://100.66.10.74:7777/phone"
    method: POST
    body: '{"app": "twitter", "action": "open"}'
    content_type: "application/json"
