# Twitter Close Tracker + Logging
# Reports to /phone when Twitter is closed

name: "Twitter Close"
category: "Telemetry"
description: "Track Twitter app closes"
enabled: true

triggers:
  - type: app_launched
    apps: ["X"]
    packages: ["com.twitter.android"]
    launched: false  # App closed

actions:
  # Log: macro triggered
  - type: shell
    command: 'mkdir -p /storage/emulated/0/MacroDroid/logs && echo "{system_time} INFO twitter-close TRIGGERED" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"app": "twitter", "action": "close"}'
    content_type: "application/json"
