# Twitter Open Tracker with Fallback + Logging
# Reports to /phone when Twitter is opened
# If server unreachable, triggers local enforcement

name: "Twitter Open"
category: "Telemetry"
description: "Track Twitter opens, fallback to local if server down"
enabled: true

variables:
  - name: response_code
    type: integer
    value: 0

triggers:
  - type: app_launched
    apps: ["X"]
    packages: ["com.twitter.android"]
    launched: true

actions:
  # Log: macro triggered
  - type: shell
    command: 'mkdir -p /storage/emulated/0/MacroDroid/logs && echo "{system_time} INFO twitter-open TRIGGERED" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"app": "twitter", "action": "open"}'
    content_type: "application/json"
    code_var: "response_code"
    block_next: true
    timeout: 5

  # Log: HTTP result
  - type: shell
    command: 'echo "{system_time} INFO twitter-open HTTP_RESULT code={lv=response_code}" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  # If server unreachable (code != 200), trigger local fallback
  - type: if
    conditions:
      - type: variable
        variable: "response_code"
        var_type: integer
        comparison: not_equals
        value: 200
        local_var: true

  # Log: fallback activated
  - type: shell
    command: 'echo "{system_time} WARN twitter-open FALLBACK server_unreachable" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  # Force run local management for this app
  - type: run_macro
    macro_name: "Twitter Management"

  # Enable all local fallbacks for future events
  - type: run_macro
    macro_name: "Enable Local Fallback"

  - type: end_if
