# YouTube Close Tracker + Logging
# Reports to /phone when YouTube is closed

name: "YouTube Close"
category: "Telemetry"
description: "Track YouTube app closes"
enabled: true

triggers:
  - type: app_launched
    apps: ["YouTube", "YouTube"]
    packages: ["com.google.android.youtube", "app.revanced.android.youtube"]
    launched: false  # App closed

actions:
  # Log: macro triggered
  - type: shell
    command: 'mkdir -p /storage/emulated/0/MacroDroid/logs && echo "{system_time} INFO youtube-close TRIGGERED" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"app": "youtube", "action": "close"}'
    content_type: "application/json"
