# YouTube Open Tracker with Fallback and Reconnection
# Reports to /phone when YouTube is opened
# Clears background flag, sends open event
# If server unreachable: triggers local enforcement
# If server reconnected: disables local fallback

name: "YouTube Open"
category: "Telemetry"
description: "Track YouTube opens, fallback to local if server down"
enabled: true

variables:
  - name: response_code
    type: integer
    value: 200

global_variables:
  - name: yt_bg
    type: boolean
    value: false

triggers:
  - type: app_launched
    apps: ["YouTube", "YouTube"]
    packages: ["com.google.android.youtube", "app.revanced.android.youtube"]
    launched: true

actions:
  # Clear background flag — YouTube is now in foreground
  - type: set_variable
    name: yt_bg
    var_type: boolean
    value: false
    local: false

  # Report open to server
  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"app": "youtube", "action": "open"}'
    content_type: "application/json"
    code_var: "response_code"
    block_next: true
    timeout: 5

  # If server unreachable (code != 200), trigger local fallback
  - type: if
    conditions:
      - type: variable
        variable: "response_code"
        var_type: integer
        comparison: not_equals
        value: 200
        local_var: true

  - type: run_macro
    macro_name: "Enable Local Fallback"

  # Else if server just came back (Connection global matches response_code)
  - type: else_if
    conditions:
      - type: variable
        variable: "Connection"
        var_type: boolean
        comparison: equals
        value: false
        local_var: false

  - type: run_macro
    macro_name: "Disable Local Fallback"

  - type: end_if
