# YouTube Close Tracker + Logging + yt_bg mini player
# Reports to /phone when YouTube is closed
# If music is still playing, sets yt_bg flag so Youtube Play/Pause
# macros handle the open/close reporting for background playback.

name: "YouTube Close"
category: "Telemetry"
description: "Track YouTube app closes"
enabled: true

global_variables:
  - name: yt_bg
    type: boolean
    value: false

triggers:
  - type: app_launched
    apps: ["YouTube", "YouTube"]
    packages: ["com.google.android.youtube", "app.revanced.android.youtube"]
    launched: false  # App closed

actions:
  # Log: macro triggered
  - type: shell
    command: 'mkdir -p /storage/emulated/0/MacroDroid/logs && echo "{system_time} INFO youtube-close TRIGGERED" >> /storage/emulated/0/MacroDroid/logs/telemetry.log'
    block: false

  # If music is still playing, YouTube is in mini player / background
  - type: if
    conditions:
      - type: music_active
        playing: true

  # Flag background playback — Youtube Play/Pause will handle reporting
  - type: set_variable
    name: yt_bg
    var_type: boolean
    value: true
    local: false

  # Wait for music to stop (background playback ended)
  - type: wait_until
    triggers:
      - type: music_playing
        started: false

  - type: end_if

  # Only report close if YouTube is NOT the active app
  # (avoids false close when just switching tabs within YouTube)
  - type: if
    conditions:
      - type: active_application
        apps: ["YouTube", "YouTube"]
        packages: ["com.google.android.youtube", "app.revanced.android.youtube"]
        negate: true

  - type: http_request
    url: "http://100.95.109.23:7777/phone"
    method: POST
    body: '{"app": "youtube", "action": "close"}'
    content_type: "application/json"

  - type: end_if
