# YouTube Gym Enable
# Auto-enables YouTube when entering the gym geofence

name: "YouTube Gym Enable"
category: "Focus"
description: "Enable YouTube when entering the gym"
enabled: true

triggers:
  - type: geofence
    geofence_id: "7fa61f1d-fcc7-4ffc-8b83-0e5b6ba0e0dd"  # Gym
    enter: true

actions:
  - type: http_request
    url: "http://100.66.10.74:7777/phone"
    method: POST
    body: '{"app": "youtube", "action": "gym_enter"}'
    content_type: "application/json"

  - type: disable_app
    apps: ["YouTube"]
    disable: false  # Enable the app

  - type: notification
    title: "Gym Mode"
    text: "YouTube enabled"
    channel_type: 0
