# YouTube Open Tracker with Fallback
# Reports to /phone when YouTube is opened
# If server unreachable, triggers local enforcement

name: "YouTube Open"
category: "Telemetry"
description: "Track YouTube opens, fallback to local if server down"
enabled: true

variables:
  - name: response_code
    type: integer
    value: 0

triggers:
  - type: app_launched
    apps: ["YouTube", "YouTube"]
    packages: ["com.google.android.youtube", "app.revanced.android.youtube"]
    launched: true

actions:
  - type: http_request
    url: "http://100.66.10.74:7777/phone"
    method: POST
    body: '{"app": "youtube", "action": "open"}'
    content_type: "application/json"
    code_var: "response_code"
    block_next: true
    timeout: 5

  # If server unreachable (code != 200), trigger local fallback
  - type: if
    conditions:
      - type: variable
        variable: "response_code"
        var_type: integer
        comparison: not_equals
        value: 200
        local_var: true

  # Force run local management for this app
  - type: run_macro
    macro_name: "Youtube management"

  # Enable all local fallbacks for future events
  - type: run_macro
    macro_name: "Enable Local Fallback"

  - type: end_if
